/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../../../eric.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube046.geometry} material={materials['Vest.001']} />
      <mesh geometry={nodes.Cube046_1.geometry} material={materials['Trouser.001']} />
      <mesh geometry={nodes.Cube046_2.geometry} material={materials['Lighting.002']} />
      <mesh geometry={nodes.Cube046_3.geometry} material={materials['Black.002']} />
      <mesh geometry={nodes.Cube046_4.geometry} material={materials['Vest Accent.001']} />
    </group>
  )
}

useGLTF.preload('../../../eric.glb')
